#!/bin/bash

BRANCH=${1:-master}

GIT_USER="https://raw.githubusercontent.com/adriansev"
REPO="alicexrd"
LOCATION="${GIT_USER}/${REPO}"


echo "This script will deploy ALICE XRootD settings for the current user"
echo "All previous template configs will be overwritten"
echo -ne "\nSpecify branch/tag; if not used default=master\n>>>>>   ${BRANCH}   <<<<<\n\n"
echo "Press ctrl-c for interrupting; waiting 10 seconds :"

for (( i=1 ; i<12 ; i++)) ; do sleep 1 ; echo -ne "." ; done
echo

CURL='curl -fkLsS -o'

XRDSHDIR=${XRDSHDIR:=~/alicexrd}
XRDCONFDIR=${XRDCONFDIR:=~/alicexrdconf}
XRDRUNDIR=${XRDRUNDIR:=~/alicexrdrun}

# create directory for logs and other files
mkdir -p ${XRDSHDIR} ${XRDRUNDIR} ${XRDCONFDIR} ${XRDCONFDIR}/manager ${XRDCONFDIR}/server

# Script for starting services
${CURL} ${XRDSHDIR}/xrd.sh               ${LOCATION}/${BRANCH}/xrd.sh && chmod +x ${XRDSHDIR}/xrd.sh

# Main configurations
${CURL} ${XRDCONFDIR}/system.cnf_CHANGEME  ${LOCATION}/${BRANCH}/alicexrdconf/system.cnf_CHANGEME

# Common configuration template
${CURL} ${XRDCONFDIR}/xrootd.xrootd.cf.tmp ${LOCATION}/${BRANCH}/alicexrdconf/xrootd.xrootd.cf.tmp

