#!/bin/bash

echo "This script will deploy ALICE XRootD settings in current user"
echo "All previous template configs will be overwritten"
sleep 10

CURL='curl -fkLsS -o'

# create directory for logs and other files
mkdir -p ~/alicexrdrun ~/alicexrd ~/alicexrdconf ~/alicexrdconf/manager ~/alicexrdconf/server

# Script for starting services
$CURL ~/alicexrd/xrd.sh               https://raw.githubusercontent.com/adriansev/alicexrd/master/xrd.sh && chmod +x ~/alicexrd/xrd.sh
$CURL ~/alicexrd/alicexrdservices.tmp https://raw.githubusercontent.com/adriansev/alicexrd/master/alicexrdservices.tmp

# Main configurations
$CURL ~/alicexrdconf/system.cnf_CHANGEME  https://raw.githubusercontent.com/adriansev/alicexrd/master/alicexrdconf/system.cnf_CHANGEME
$CURL ~/alicexrdconf/crontab.xrootd.tmp   https://raw.githubusercontent.com/adriansev/alicexrd/master/alicexrdconf/crontab.xrootd.tmp
$CURL ~/alicexrdconf/authz.cnf            https://raw.githubusercontent.com/adriansev/alicexrd/master/alicexrdconf/authz.cnf

# Manager templates
$CURL ~/alicexrdconf/manager/xrootd.dpm.cf.tmp    https://raw.githubusercontent.com/adriansev/alicexrd/master/alicexrdconf/manager/xrootd.dpm.cf.tmp
$CURL ~/alicexrdconf/manager/xrootd.xrootd.cf.tmp https://raw.githubusercontent.com/adriansev/alicexrd/master/alicexrdconf/manager/xrootd.xrootd.cf.tmp

# Server templates
$CURL ~/alicexrdconf/server/xrootd.dpm.cf.tmp     https://raw.githubusercontent.com/adriansev/alicexrd/master/alicexrdconf/server/xrootd.dpm.cf.tmp
$CURL ~/alicexrdconf/server/xrootd.xrootd.cf.tmp  https://raw.githubusercontent.com/adriansev/alicexrd/master/alicexrdconf/server/xrootd.xrootd.cf.tmp

